# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту mihanchik94@gmail.com если сборка упала
notifications:
  email:
    recipients:
      - mihanchik94@gmail.com
    on_success: never # default: change
    on_failure: always # default: always

env:
 global:
  - CODECOV_TOKEN="4c070b4e-849c-4559-b3da-62d94d32cb4a"